# BINDINGS
## Change prefix binding from default C-b
unbind C-space
set -g prefix C-Space
bind C-Space send-prefix

## Vim motions for changing windows
bind l next-window
bind h previous-window

## Bind to reload the session configuration
bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded!"

## Preserve path on creating new windows
bind c new-window -c "#{pane_current_path}"

## Allow scrolling with the touchpad/mouse when in alternate views, i.e in man
bind -n WheelUpPane {
	if -F '#{||:#{pane_in_mode},#{mouse_any_flag}}' {
		send -M
	} {
		if -F '#{alternate_on}' { send-keys -N 3 Up } { copy-mode -e }
	}
}
bind -n WheelDownPane {
	if -F '#{||:#{pane_in_mode},#{mouse_any_flag}}' {
		send -M
	} {
		if -F '#{alternate_on}' { send-keys -N 3 Down }
	}
}

# OPTIONS
set-option -g history-limit 10000
set -g mode-keys vi
## Enable mouse usage
set -g mouse on

## Window/tile numbering
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

## neovim stuff
set-option -g editor /usr/bin/nvim
set-option -g focus-events on

# STATUS BAR
set-option -g status-position top
set-option -g status-justify absolute-centre
set-option -g status-keys vi
set-option -g status-style bg=terminal
set-option -g status-left "session: #S"
set-option -g status-right ""
set-option -g message-style bg=default,fg=default
set-option -g window-status-current-style bold
set-option -g window-status-current-format "#{window_index}:#{window_name}"

